### ISSUE TITLE
question on yarn dev

### ISSUE THREAD

**Issue by YOGESH256** [leemonade/leemons#30]
![image](https://user-images.githubusercontent.com/67831090/209858441-2e505b9c-a35e-4c23-981e-177821f3b16f.png)

what happened here! can anyone guide me! followed all the steps in https://github.com/leemonade/leemons-docs/blob/main/docs/getting-started/installation.mdx  I installed the packages in demo folder and then encountered this error!

**Comment by MIGUELez11** [comment]
It's an erro while trying to gzip the previous log file, you can remove the folder `leemons/examples/demo/logs`, it should work again, maybe a corrupted file? 🤔

**Comment by YOGESH256** [comment]
Thanks for responding!  Server started 👏
Could u take a look at this! I logged the error! 
![image](https://user-images.githubusercontent.com/67831090/210070364-28a0efb2-2118-47f6-9571-7afb64845c00.png)

**Comment by MIGUELez11** [comment]
Sorry about the delay of the response, I've been looking through it, and the problem is the frontend symlinks, it should be done with a library like [lnk](https://www.npmjs.com/package/lnk).

To pass through it, you can use WSL, in windows, I've been recently working on the Windows OS, and had the same problem, so I've been using WSL and it works like a charm.

**Comment by MIGUELez11** [comment]
A bug has been created to move from fs links to the [lnk](https://www.npmjs.com/package/lnk) library

**Comment by aurk** [comment]
Hello @MIGUELez11 
I've also faced same issue and now using WSL. server started successfully but when executing `yarn front` I'm getting this issue:
![image](https://user-images.githubusercontent.com/6688083/234262976-44c7803d-7d51-4c8c-b07a-e74a3bb721e2.png)

Please note that I did not follow step # 5: Bulk data creation template configuration

**Comment by MIGUELez11** [comment]
🤔 Looks like another error, it's not finding prosemirror-state, for now, we have two options until it gets fixed.

The first and most recommended is [using docker ](https://leemonade.github.io/leemons-docs/getting-started/dockerInstallation) which mught be most recommended since it's been tested as it is (docker is like a VM, so the system is the same for everyone, this doesn't necessarily happen on WSL)


And the other one is to install manualy the dependencies, it's known that sometimes this ones fails to install, so run the following command at `examples/demo` 

```sh
yarn add @tiptap/pm prosemirror-commands prosemirror-keymap prosemirror-model prosemirror-schema-list prosemirror-state prosemirror-transform prosemirror-view prosemirror-dropcursor prosemirror-gapcursor prosemirror-history
```

**Comment by MIGUELez11** [comment]
Due to inactivity I close this issue.

The previous answer should work for this issue.
