### ISSUE TITLE
Unable to assign tasks to students - "An error occurred while getting assignables"

### ISSUE THREAD

**Issue by fmniloyuk** [leemonade/leemons#43]
I am experiencing difficulties assigning tasks to students using the tutor account. Whenever I attempt to assign a task, I receive the following error message: "An error occurred while getting assignables." I have also attempted to assign the same task by creating a custom group, but unfortunately, the same error message persists. As a result, it is currently impossible to assign tasks to students.

This issue significantly hampers the functionality and effectiveness of the platform in facilitating task management and student engagement. It would be immensely helpful if this issue could be investigated and resolved promptly, enabling tutors to assign tasks to students without encountering any errors.

**Comment by MIGUELez11** [comment]
After reviewing it with @fmniloyuk, we've seen is due to sql ending the transactions before ending, the solution is to either increase the transaction max live time, or as we've done, to enable `Leemons Custom Transactions`

This is done by adding to your `.env` file the following line `USE_CUSTOM_ROLLBACK=true`
