### ISSUE TITLE
How I can skip aws iot setup?

### ISSUE THREAD

**Issue by ziad696** [leemonade/leemons#50]
i want  skip this, is there any way possible?
![image](https://github.com/leemonade/leemons/assets/66814551/8600533f-c7c5-4216-881f-e69ade4eaa29)

**Comment by ziad696** [comment]
Hello, I have uninstall it but when i go to installation page and repeat the installation, however after i at "admins users" section, i click save and continue, its showing just white screen instead like before which  navigate to aws iot section, so i believe its the uninstallation of aws iot is caused this

**Comment by MIGUELez11** [comment]
Okay, while I do further investigations, I suppose you can install it back again with `yarn add leemons-plugin-mqtt-aws-iot@0.0.1` and fill in the fields with dummy data (as far as I know, if not specified in env, it's supposed to use socket.io for chats.

**Comment by MIGUELez11** [comment]
Hello again, I've taken a look to the admin code and aws-iot config step is registered at the `leemons-plugin-mqtt-aws-iot` plugin installation, so even after being deleted, it still renders the step, so if you want to remove this step, you can run the following query in your sql database:

```sql
DELETE FROM `plugins_widgets::widget-item` WHERE zoneKey = "plugins.admin.admin-page" AND `key` = "plugins.mqtt-aws-iot.admin.config";
```

You can also uninstall the plugin, because you won't need it :D

**Comment by ziad696** [comment]
Hi, thanks for the response? as you say its work and not render the step.... However i on last step for AWS S3 is AWS S3 also required?

**Comment by MIGUELez11** [comment]
S3 is an optional provider, if not filled, it will use the file system

**Comment by ziad696** [comment]
okay, thank you
