### ISSUE TITLE
How to setup a SMPT provider (specially Gmail)

### ISSUE THREAD

**Issue by T0ny-dev** [leemonade/leemons#51]
estoy configurando la plataforma y utilice docker-compose para crear los contenedores, el detalle es que no he podido configurar exitosamente un provedor de SMTP siguiendo la guias de GMAIL, me gustaria si me pudieran compartir un ejemplo con https://www.wpoven.com/tools/free-smtp-server-for-testing de como se configura ya que no he podido avanzar de las configuracions para asignar admnistradores porque no llegan los correos para activar las cuentas. saludos :)

![image](https://github.com/leemonade/leemons/assets/103908962/5ab3986a-4077-467f-b87b-625b35754f89)

**Comment by MIGUELez11** [comment]
Hola, debido a la importancia del issue, voy a responder en inglés, aún así, si luego tienes cualquier duda, te puedo seguir ayudando.

When using Google as your email provider, it's important to understand that **Gmail has multiple layers of security in place**. **First and foremost, you need to determine whether or not you have two-step authentication (2FA) enabled**. Depending on this configuration, the setup process will vary.

**How can you check if 2FA is enabled?** 
[You can follow this steps provided by Google](https://support.google.com/accounts/answer/185839?hl=en&co=GENIE.Platform%3DDesktop) . When you reach the step just before enabling it, you will be able to see whether it was already activated or not.

`If you have 2FA enabled`:

Google itself states that there are different ways to use their services with third-party applications. The first method is OAuth (the 'Sign in with Google' button), and **the other method is for applications that don't support signing in with Google** (like the current case with Leemons). This method involves generating a unique password for the service called `App passwords`, and you can configure it following [this Google's instructions](https://support.google.com/accounts/answer/185833?visit_id=638218219855312963-2200404512&p=InvalidSecondFactor&rd=1).

To configure this password, I recommend selecting the mail service and then choosing 'Other' > entering a text that you will identify with your Leemons installation.

`If you don't have 2FA enabled`:

In this case, there shouldn't be a major issue apart from entering your account password. However, since this is very insecure, I recommend enabling 2FA and generating an App Password as described in the 'If you have 2FA enabled' section.

**Comment by T0ny-dev** [comment]
Thank you very much, the problem is fixed, that way my mistake is that I didn't turn on the security switch and generate a new password app in google account.

Gracias problema resuelto, no había activado el switch de seguridad y pese ya tener generado una contraseña, generar una nueva lo soluciono.
